### ISSUE TITLE
Should we remove 'use-strict'?

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-modulizer#181]
Should this remove the `'use strict';` declaration since it is always enabled in modules?

**Comment by justinfagnani** [comment]
I think this is fixed

**Comment by stramel** [comment]
@justinfagnani I am still seeing a `'use strict';` in marked-element 3.0 branch

**Comment by justinfagnani** [comment]
Huh, I didn't see it in other elements, but I guess they didn't have 'use strict' in the first place.

**Comment by justinfagnani** [comment]
@stramel are you inclined to take this one?

**Comment by stramel** [comment]
@justinfagnani I will take a look again. I did some initial looking around when I filed this issue.
